version: '3'
services:
  api-js:
    container_name: "dashboard-api-js"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
    volumes:
      - .:/app
    networks:
      - dashboard-network

networks:
  dashboard-network:
    external:
      name: dashboard-network