version: '3'
services:
  redis:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '6379:6379'
    networks:
      - dashboard-network
    container_name: redis

networks:
  dashboard-network:
    external:
      name: dashboard-network